export const helpCategories = [
  { id: "getting-started", label: "Getting started" },
  { id: "sources-imports", label: "Sources & imports" },
  { id: "clusters", label: "Clusters" },
  { id: "search-retrieval", label: "Search & retrieval" },
  { id: "chat-answers", label: "Chat & answers" },
  { id: "odin-projects", label: "Odin projects" },
  { id: "map-connections", label: "Map & connections" },
  { id: "tasks-automation", label: "Tasks & background work" },
  { id: "models-ocr", label: "Models & OCR" },
  { id: "storage-backups", label: "Storage & backups" },
  { id: "connections-sharing", label: "Connections & sharing" },
  { id: "privacy-security", label: "Privacy & security" },
  { id: "troubleshooting", label: "Troubleshooting" },
] as const;

export type HelpCategoryId = (typeof helpCategories)[number]["id"];
export type HelpVisualKind =
  | "sources"
  | "clusters"
  | "search"
  | "chat"
  | "project"
  | "map"
  | "tasks"
  | "models"
  | "storage"
  | "connections"
  | "settings";

export type HelpArticle = {
  id: string;
  category: HelpCategoryId;
  title: string;
  summary: string;
  explanation: string[];
  steps: string[];
  path: string;
  commands?: Array<{ command: string; description: string }>;
  plan: string[];
  related: string[];
  visual: {
    kind: HelpVisualKind;
    title: string;
    highlight: string;
    caption: string;
  };
};

type CompactHelpArticle = Omit<HelpArticle, "explanation" | "visual"> & {
  explanation: string;
  visual: [HelpVisualKind, string, string];
};

const compactHelpArticle = (article: CompactHelpArticle): HelpArticle => ({
  ...article,
  explanation: [article.explanation],
  visual: {
    kind: article.visual[0],
    title: article.title,
    highlight: article.visual[1],
    caption: article.visual[2],
  },
});

const additionalHelpArticles: HelpArticle[] = [
  compactHelpArticle({
    id: "vault-core-concepts", category: "getting-started", title: "What are sources, clusters, chats, projects, and maps?",
    summary: "Sources are the evidence; the other views organize, retrieve, explain, or connect that evidence.",
    explanation: "A source is one imported item. Clusters group related sources. Chat retrieves passages and writes cited answers. Odin projects add code-aware snapshots and relationships. Maps visualize connections; they do not create new evidence.",
    steps: ["Add evidence in Sources.", "Review its organization in Clusters.", "Ask questions in Chat with a deliberate scope.", "Use Projects for code repositories and Map for relationships."],
    path: "Sources → Clusters → Chat; Projects for code; Map for relationships",
    plan: ["Ingest evidence once.", "Build several derived views from the same evidence.", "Keep every answer and connection traceable to a source."],
    related: ["first-ten-minutes", "search-versus-chat", "folder-import-vs-project"],
    visual: ["sources", "Sources", "Start with evidence; every other Vault view depends on it."],
  }),
  compactHelpArticle({
    id: "which-feature-to-use", category: "getting-started", title: "Which Vault feature should I use for my task?",
    summary: "Use Sources to collect, Search to locate, Chat to synthesize, Clusters to organize, and Map to inspect relationships.",
    explanation: "Choose the smallest tool that answers the question. Search is fastest for finding a known phrase or file. Chat is better for synthesis. Clusters expose themes. Map is useful only when the relationship itself matters.",
    steps: ["Need a file or phrase? Use Search.", "Need an explanation across evidence? Use Chat.", "Need to tidy themes? Use Clusters.", "Need code structure? Use an Odin project.", "Need relationship context? Use Map."],
    path: "Search / Chat / Clusters / Projects / Map",
    plan: ["Narrow the evidence first.", "Use the matching retrieval or visualization tool.", "Verify important results through sources and citations."],
    related: ["vault-core-concepts", "search-versus-chat", "choose-chat-scope"],
    visual: ["search", "Search", "Start with Search when you already know what you are looking for."],
  }),
  compactHelpArticle({
    id: "closing-vault-background-work", category: "getting-started", title: "Does work continue after I close Vault?",
    summary: "Normal background work is durable, but fully quitting the desktop application stops its local workers until the next launch.",
    explanation: "Navigating away does not cancel an import, reindex, or metric job. Closing the window may quit the desktop application depending on platform behavior; queued work remains recorded and resumes safely when services return.",
    steps: ["Check Tasks before quitting.", "Pause cancellable work if you need to stop intentionally.", "Relaunch Vault later.", "Confirm queued or interrupted work resumes instead of starting duplicate jobs."],
    path: "Tasks → Active → pause or leave running",
    plan: ["Persist job state before execution.", "Stop workers safely during application shutdown.", "Resume eligible work from its durable state after restart."],
    related: ["task-statuses", "pause-resume-cancel", "restart-services"],
    visual: ["tasks", "Active", "Tasks is the authoritative place to see whether background work is still running."],
  }),

  compactHelpArticle({
    id: "supported-source-types", category: "sources-imports", title: "Which files and source types can I add?",
    summary: "Vault supports common documents, text, code, images through OCR, links, pasted notes, audio or video transcripts, and folder imports.",
    explanation: "Support depends on an available extractor. A file can be accepted but still require OCR, a transcript provider, or a compatible parser. The import preview and failure detail identify unsupported or unreadable items.",
    steps: ["Choose Add files, Add link, Paste text, or Import folder.", "Review the native file picker filter.", "Watch the import summary for skipped items.", "Open any failed source to see the missing extractor."],
    path: "Sources → Add files / Add link / Paste text / Import folder",
    plan: ["Identify source type.", "Choose the matching extractor.", "Normalize extracted content into pages or chunks.", "Index only validated content."],
    related: ["skipped-import-files", "scanned-documents-ocr", "retry-failed-source"],
    visual: ["sources", "Add files", "The add controls separate file, link, text, folder, and project workflows."],
  }),
  compactHelpArticle({
    id: "folder-import-vs-files", category: "sources-imports", title: "Should I add individual files or import a folder?",
    summary: "Use individual files for a small selection; use a folder when its nested structure and future additions matter.",
    explanation: "Folder imports retain the import root and relative paths, which lets Sources reconstruct nested folders. Individual files are simpler and do not create a folder grouping.",
    steps: ["Use Add files for a hand-picked set.", "Use Import folder for a maintained collection.", "Open the folder row in Sources to browse subfolders.", "Use an Odin project instead when code structure and Git changes matter."],
    path: "Sources → Add files or Import folder",
    plan: ["Record the import root for folder imports.", "Preserve relative paths.", "Group the Sources view without changing source identity."],
    related: ["folder-import-vs-project", "duplicate-sources", "sync-folder-changes"],
    visual: ["sources", "Import folder", "Folder import keeps nested structure; Add files creates standalone sources."],
  }),
  compactHelpArticle({
    id: "duplicate-sources", category: "sources-imports", title: "What happens if I import the same source twice?",
    summary: "Vault tries to recognize the same file or URL, but moved, copied, or materially changed inputs may become separate sources.",
    explanation: "Identity can use paths, import roots, URLs, fingerprints, and content. A duplicate warning protects against accidental repetition; separate copies may still be useful when they belong to different maintained collections.",
    steps: ["Search the title before importing again.", "Compare original paths and summaries in the inspectors.", "Keep the source with the correct maintained path.", "Delete only the redundant source after verifying citations and project membership."],
    path: "Sources → Search → select each possible duplicate",
    plan: ["Compare stable identity and content fingerprints.", "Reuse an existing source when identity is certain.", "Keep ambiguous copies separate rather than merging evidence silently."],
    related: ["delete-source-effects", "folder-import-vs-files", "source-statuses"],
    visual: ["sources", "Search sources", "Search before importing when you suspect the item is already present."],
  }),
  compactHelpArticle({
    id: "skipped-import-files", category: "sources-imports", title: "Why were some files skipped during a folder import?",
    summary: "Vault skips unsupported, hidden, temporary, generated, symlinked, or unreadable files to keep imports safe and useful.",
    explanation: "Build directories and symlinks can be huge or escape the selected folder. Temporary and unsupported files usually add noise. The batch summary distinguishes skipped items from failures that created a source record.",
    steps: ["Open the final import summary.", "Check whether the item was skipped or failed.", "Move a genuinely useful file into a supported readable format.", "Import that file directly if it should bypass the folder exclusions."],
    path: "Sources → Import progress → final summary",
    plan: ["Walk the selected folder without following symlinks.", "Apply safety and support filters.", "Queue accepted files and report skipped counts separately."],
    related: ["supported-source-types", "batch-upload-progress", "retry-failed-source"],
    visual: ["sources", "Skipped", "Skipped means no source was created; Failed means a source has retryable diagnostics."],
  }),
  compactHelpArticle({
    id: "scanned-documents-ocr", category: "sources-imports", title: "How do scanned PDFs and images become searchable?",
    summary: "Vault uses OCR when a page has little or no extractable text and an OCR runtime is ready.",
    explanation: "OCR reads pixels, so quality depends on resolution, orientation, language, contrast, and handwriting. The original remains the source of truth; OCR text is a searchable derived layer.",
    steps: ["Confirm OCR is Ready in Settings → Models & search.", "Import the scan normally.", "Open source pages and inspect extracted text.", "Correct orientation or image quality and reindex if the output is unusable."],
    path: "Settings → Models & search → OCR; Sources → source → Pages",
    plan: ["Detect pages without useful embedded text.", "Run OCR with configured language support.", "Store page-aligned text.", "Index it while preserving the original file."],
    related: ["ocr-language-quality", "model-roles", "retry-failed-source"],
    visual: ["models", "OCR Ready", "OCR readiness is separate from the chat and embedding models."],
  }),
  compactHelpArticle({
    id: "delete-source-effects", category: "sources-imports", title: "What changes when I delete a source?",
    summary: "The source and its derived index data are removed from Vault; the original external file is not deleted unless explicitly stated.",
    explanation: "Deleting a source removes its chunks, embeddings, cluster membership, and future retrieval. Existing chat history can retain citation labels, but the underlying source may no longer open.",
    steps: ["Open the source inspector and verify its path.", "Check whether important chats or projects depend on it.", "Use the confirmed Delete action.", "Reimport the original later if the deletion was intentional but temporary."],
    path: "Sources → select source → Delete",
    plan: ["Confirm source identity.", "Remove derived relationships and indexes transactionally.", "Preserve unrelated files and sources."],
    related: ["delete-cluster-effects", "duplicate-sources", "backup-vault"],
    visual: ["sources", "Delete source", "The confirmation describes Vault data separately from the original file."],
  }),

  compactHelpArticle({
    id: "unclustered-collection", category: "clusters", title: "Is Unclustered sources a real cluster?",
    summary: "It is a live collection of indexed sources without a cluster assignment, not a stored semantic cluster.",
    explanation: "The collection changes automatically when sources are assigned or removed. It has no independent profile or color, but it can be opened in Sources and selected as a Chat scope.",
    steps: ["Open Clusters and select Unclustered sources.", "Review or search the complete collection.", "Ask it questions from Chat if needed.", "Assign sources only when the destination is clear."],
    path: "Clusters → Unclustered sources; Chat → Unclustered sources",
    plan: ["Count indexed sources with no cluster ID.", "Expose them as one predictable review surface.", "Remove each source from the collection as soon as assignment succeeds."],
    related: ["ready-not-clustered", "ask-unclustered", "how-clustering-works"],
    visual: ["clusters", "Unclustered sources", "This collection is calculated from current membership rather than stored as a normal cluster."],
  }),
  compactHelpArticle({
    id: "move-merge-clusters", category: "clusters", title: "When should I move a source or merge two clusters?",
    summary: "Move one misplaced source; merge clusters only when their overall subjects and future use are genuinely the same.",
    explanation: "A move changes one membership. A merge affects every source, chats or links scoped to the clusters, and the combined profile. Review merge artifacts and the destination before confirming.",
    steps: ["Compare cluster descriptions and representative sources.", "Move isolated mistakes individually.", "Use Merge only for duplicate concepts.", "Review the merge artifact and undo path immediately after completion."],
    path: "Cluster → Sources → Move; Clusters → Manage → Merge",
    plan: ["Validate source and cluster identities.", "Apply membership changes atomically.", "Refresh affected profiles and retain merge evidence for reversal."],
    related: ["delete-cluster-effects", "how-clustering-works", "cluster-source-list"],
    visual: ["clusters", "Move", "Use the narrowest action that fixes the organization problem."],
  }),
  compactHelpArticle({
    id: "delete-cluster-effects", category: "clusters", title: "Does deleting a cluster delete its sources?",
    summary: "No. Deleting a cluster preserves its sources and returns them to the unclustered collection.",
    explanation: "The cluster profile, membership, and cluster-specific views are removed. Source records and original files remain. Scoped chats may keep history but can no longer retrieve through the deleted cluster.",
    steps: ["Open Manage cluster.", "Read the source-preservation confirmation.", "Delete the cluster.", "Review the sources under Unclustered sources and reassign them if needed."],
    path: "Cluster → Manage → Delete cluster",
    plan: ["Detach source memberships.", "Remove cluster-derived profile data.", "Preserve source records and surface them as unclustered."],
    related: ["unclustered-collection", "delete-source-effects", "move-merge-clusters"],
    visual: ["clusters", "Delete cluster", "The confirmation should explicitly say that sources are preserved."],
  }),

  compactHelpArticle({
    id: "search-versus-chat", category: "search-retrieval", title: "When should I use Search instead of Chat?",
    summary: "Use Search to locate evidence; use Chat to combine and explain evidence.",
    explanation: "Search returns ranked sources or passages without generating a narrative. Chat adds model interpretation, which is useful for synthesis but should be verified through citations.",
    steps: ["Use Search for a filename, phrase, person, or known fact.", "Open the source to verify it directly.", "Use Chat when the question spans several sources.", "Follow citations for consequential answers."],
    path: "Search for retrieval; Chat for synthesis",
    plan: ["Search ranks matching evidence.", "Chat retrieves evidence, builds context, and generates a cited response.", "Both use the same indexed source material."],
    related: ["which-feature-to-use", "exact-vs-semantic-search", "open-citation"],
    visual: ["search", "Search", "Search is the fastest path when you need the evidence itself."],
  }),
  compactHelpArticle({
    id: "exact-vs-semantic-search", category: "search-retrieval", title: "Why does Search find related wording instead of the exact phrase?",
    summary: "Vault can combine lexical matching with semantic similarity, so conceptually related text may rank beside exact words.",
    explanation: "Exact matching is strongest for identifiers, filenames, quoted phrases, and uncommon terms. Semantic matching helps when the source uses different wording. Filters and more specific queries reduce broad matches.",
    steps: ["Use distinctive terms or the exact filename.", "Add source-type or cluster filters.", "Open a result and inspect the matched excerpt.", "Use Chat only after the relevant source set is clear."],
    path: "Search → query → filters → result excerpt",
    plan: ["Find lexical and semantic candidates.", "Apply active filters.", "Blend and rank evidence while retaining source identity."],
    related: ["search-versus-chat", "search-no-results", "search-filters-ranking"],
    visual: ["search", "Result excerpt", "The excerpt shows why a semantically related result matched."],
  }),
  compactHelpArticle({
    id: "search-filters-ranking", category: "search-retrieval", title: "How do filters change search results?",
    summary: "Filters define the eligible source set before ranking, so a narrow filter can hide an otherwise strong match.",
    explanation: "Cluster, project, type, date, and status constraints should agree with where the source actually lives. Clear filters when results look unexpectedly small, then reapply them one at a time.",
    steps: ["Read every active filter.", "Clear filters and repeat the same query.", "Confirm the expected source appears.", "Reapply only the constraints needed for the task."],
    path: "Search → active filters → Clear → reapply",
    plan: ["Build the eligible source set.", "Retrieve matching passages only from that set.", "Rank and paginate without changing the filter contract."],
    related: ["exact-vs-semantic-search", "search-no-results", "choose-chat-scope"],
    visual: ["search", "Clear filters", "Clear filters first when a known source disappears."],
  }),
  compactHelpArticle({
    id: "search-no-results", category: "search-retrieval", title: "Why does Search return no results for a source I can see?",
    summary: "The source may be filtered out, not yet indexed, grouped under a project, or indexed with text different from the query.",
    explanation: "A visible source record does not guarantee searchable chunks. Check Ready status and chunk count, clear filters, search the exact title, then reindex search only if the source remains absent.",
    steps: ["Open the source inspector and confirm Ready plus a nonzero chunk count.", "Clear Search filters.", "Search its exact title or a phrase from extracted text.", "Reindex the source before considering a vault-wide search rebuild."],
    path: "Sources → source details; Search → clear filters; Source → Reindex",
    plan: ["Verify searchable chunks exist.", "Remove accidental scope constraints.", "Repair only the smallest stale index surface."],
    related: ["source-statuses", "rebuild-search-index", "search-filters-ranking"],
    visual: ["search", "No results", "Check indexing and filters before rebuilding the entire search index."],
  }),
  compactHelpArticle({
    id: "rebuild-search-index", category: "search-retrieval", title: "When should I rebuild the search index?",
    summary: "Use a vault-wide rebuild only when many Ready sources are missing or diagnostics report index drift.",
    explanation: "Reindexing one source is cheaper and safer for an isolated problem. A full rebuild is durable background work and can temporarily reduce retrieval completeness while new data is validated.",
    steps: ["Test more than one known source.", "Check System health and Tasks for index drift.", "Retry an individual source when the problem is isolated.", "Use Reindex vault search only for a confirmed broad inconsistency."],
    path: "Settings → Models & search → Reindex vault search",
    plan: ["Scan current indexed sources.", "Rebuild searchable chunks and embeddings in background jobs.", "Publish validated index generations without deleting good data early."],
    related: ["search-no-results", "task-statuses", "model-roles"],
    visual: ["settings", "Reindex vault search", "A vault-wide rebuild is a repair action, not routine maintenance."],
  }),

  compactHelpArticle({
    id: "partial-chat-answer", category: "chat-answers", title: "Why does Chat say an answer is partial or incomplete?",
    summary: "Vault found useful evidence but could not cover every requested part within the selected scope or retrieval limits.",
    explanation: "Partial is an honesty signal, not necessarily a model failure. The coverage details can identify missing clusters, excluded sources, truncated retrieval, or unavailable project interpretation.",
    steps: ["Read the coverage or warning text below the answer.", "Open the cited evidence.", "Broaden the scope only if the missing material should be included.", "Ask a narrower follow-up for the uncovered part."],
    path: "Chat → answer → coverage details / warnings",
    plan: ["Compare requested facets with retrieved evidence.", "Mark uncovered facets explicitly.", "Preserve useful cited output instead of presenting it as complete."],
    related: ["choose-chat-scope", "open-citation", "regenerate-chat-answer"],
    visual: ["chat", "Partial answer", "Coverage warnings explain what the answer could and could not support."],
  }),
  compactHelpArticle({
    id: "chat-attachments", category: "chat-answers", title: "What is the difference between attaching a file and importing it?",
    summary: "An attachment is conversation context; an imported source becomes a durable, searchable part of the vault.",
    explanation: "Use attachments for temporary questions or files you do not want organized. Import material that should appear in Search, Clusters, Map, future chats, or project context.",
    steps: ["Attach a file for a one-off conversation.", "Review the attachment notice before sending.", "Import it through Sources if it should persist.", "Use citations to distinguish durable sources from temporary context."],
    path: "Chat → Attach files; Sources → Add files for durable import",
    plan: ["Include attachments in the current generation context.", "Avoid silently adding them to the vault.", "Persist only through an explicit source import."],
    related: ["supported-source-types", "choose-chat-scope", "chat-history-saving"],
    visual: ["chat", "Attach files", "Attachment is temporary unless you separately import the file as a source."],
  }),
  compactHelpArticle({
    id: "regenerate-chat-answer", category: "chat-answers", title: "When should I retry or regenerate an answer?",
    summary: "Retry after a runtime interruption; regenerate when you want a new answer from the same user question and scope.",
    explanation: "Changing scope, sources, or the question is not a regeneration—it is a new request. Keep the original answer when comparing results, and use citations rather than phrasing alone to judge improvement.",
    steps: ["Retry if the answer stopped because the model or service failed.", "Regenerate when the run completed but another synthesis may help.", "Change scope explicitly before asking a broader question.", "Compare evidence coverage and citations."],
    path: "Chat → answer actions → Retry or Regenerate",
    plan: ["Reuse the linked user message.", "Create a new generation record.", "Keep prior output for history and comparison."],
    related: ["partial-chat-answer", "choose-chat-scope", "model-unavailable"],
    visual: ["chat", "Analyze again", "Retry repairs an interrupted run; regenerate creates another completed attempt."],
  }),

  compactHelpArticle({
    id: "folder-import-vs-project", category: "odin-projects", title: "What is the difference between a folder import and an Odin project?",
    summary: "A folder import preserves files and folders; an Odin project additionally understands code structure, snapshots, Git changes, and symbol relationships.",
    explanation: "Use a normal folder for documents or code you only need to search. Register an Odin project when entrypoints, dependencies, change impact, interpretation, or project maps are important.",
    steps: ["Use Import folder for ordinary searchable files.", "Use Projects → Add project folder for code-aware analysis.", "Do not register the same root both ways unless you intentionally want separate records.", "Open the project readiness rows after registration."],
    path: "Sources → Import folder; Projects → Add project folder",
    commands: [{ command: "odin project add [path] --name \"Project name\"", description: "Register the folder as a code-aware Odin project." }],
    plan: ["Discover the repository and manifest.", "Create a primary project cluster.", "Build structure, retrieval, graph, and optional interpretation layers."],
    related: ["folder-import-vs-files", "project-snapshots", "odin-interpretation"],
    visual: ["project", "Add project folder", "Choose a project only when code-aware derived layers are useful."],
  }),
  compactHelpArticle({
    id: "project-snapshots", category: "odin-projects", title: "What is an Odin project snapshot?",
    summary: "A snapshot is the validated project state that structure, retrieval, interpretation, and graph outputs refer to.",
    explanation: "Snapshots prevent half-updated project views. New changes build candidate outputs first; Vault activates them together only after validation. The working tree can be dirty while the active snapshot remains internally consistent.",
    steps: ["Open the project and read Indexed commit and Working tree status.", "Treat Active snapshot as the currently answerable state.", "Preview changes before syncing.", "Sync when you want the active snapshot to include them."],
    path: "Projects → project → Snapshot and repository status",
    commands: [{ command: "odin project status [path]", description: "Show active snapshot and repository freshness." }],
    plan: ["Fingerprint current files.", "Build a candidate snapshot and derived layers.", "Validate cross-layer consistency.", "Promote the candidate atomically."],
    related: ["sync-project-changes", "odin-interpretation", "odin-graph-metrics"],
    visual: ["project", "Active snapshot", "Repository changes do not alter the active answerable snapshot until sync succeeds."],
  }),
  compactHelpArticle({
    id: "sync-project-changes", category: "odin-projects", title: "How do I bring current code changes into an Odin project?",
    summary: "Preview the change set, then sync or reindex the smallest required project layers.",
    explanation: "Automatic sync can apply ordinary changes when enabled. Manual or notify mode leaves the active snapshot unchanged until you approve work. Deleted, renamed, or large structural changes may require more layers than a text-only edit.",
    steps: ["Open project Changes or run the changes command.", "Review added, changed, deleted, and renamed files.", "Choose Sync.", "Wait for the new snapshot and required derived layers to become Ready."],
    path: "Projects → project → Changes → Sync",
    commands: [{ command: "odin project changes [path]", description: "Preview without indexing." }, { command: "odin project sync [path]", description: "Apply current file changes." }],
    plan: ["Calculate the repository delta.", "Reuse unaffected derived work.", "Rebuild impacted layers.", "Promote the validated snapshot."],
    related: ["project-snapshots", "reindex-project-layers", "closing-vault-background-work"],
    visual: ["project", "Sync changes", "Preview the delta before replacing the active project snapshot."],
  }),
  compactHelpArticle({
    id: "reindex-project-layers", category: "odin-projects", title: "Which Odin project layer should I reindex?",
    summary: "Rebuild only the failed or stale layer unless diagnostics show that an earlier dependency is invalid.",
    explanation: "Manifest feeds structure; structure feeds graph and interpretation; retrieval depends on indexed project content. A full rebuild is appropriate only when several dependent layers disagree or the active snapshot is invalid.",
    steps: ["Read project readiness from top to bottom.", "Find the first stale or failed dependency.", "Reindex that layer.", "Use full only when multiple layers or the snapshot contract are broken."],
    path: "Project → Intelligence readiness → Reindex layer",
    commands: [{ command: "odin project reindex [path] --layer structure", description: "Replace structure with manifest, retrieval, interpretation, graph, or full as diagnosed." }],
    plan: ["Validate prerequisite layers.", "Rebuild the selected derived output.", "Refresh downstream outputs only when their dependency changed."],
    related: ["odin-interpretation", "odin-graph-metrics", "project-snapshots"],
    visual: ["project", "Reindex layer", "Start with the first failed dependency instead of defaulting to a full rebuild."],
  }),

  compactHelpArticle({
    id: "map-connection-modes", category: "map-connections", title: "What is the difference between Current and Semantic connections?",
    summary: "Current connections are stored relationships; Semantic connections are similarity-based suggestions calculated from content.",
    explanation: "Current edges are stronger evidence that a relationship was explicitly derived or saved. Semantic edges are useful for discovery but can be broad, so their score and supporting sources matter.",
    steps: ["Open Map and note the active mode.", "Use Current for established structure.", "Use Semantic to discover related material.", "Select an edge or node to inspect why it appears."],
    path: "Map → Current connections / Semantic connections",
    plan: ["Load eligible nodes.", "Choose stored edges or scored similarity edges.", "Render only edges whose endpoints are visible."],
    related: ["map-no-connections", "map-dense-or-wrong", "map-show-more"],
    visual: ["map", "Current / Semantic", "The selected mode changes what an edge means."],
  }),
  compactHelpArticle({
    id: "map-dense-or-wrong", category: "map-connections", title: "What should I do when the map is too dense or a connection looks wrong?",
    summary: "Narrow the question or filters, switch connection mode, and inspect the evidence behind the specific edge.",
    explanation: "Dense graphs trade completeness for readability. Labels may be hidden until selection. A semantic connection can be plausible but unhelpful; a current connection should have stored evidence that can be inspected or repaired.",
    steps: ["Narrow the project question or cluster filter.", "Switch between Current and Semantic.", "Select the suspicious connection.", "Open its sources and report or repair the underlying relationship rather than judging line position."],
    path: "Map → filter or ask → select connection → evidence",
    plan: ["Reduce the visible node set.", "Recalculate eligible edges.", "Defer labels and details until selection for performance."],
    related: ["map-connection-modes", "map-show-more", "open-citation"],
    visual: ["map", "Connection details", "Inspect evidence before deciding that an edge is incorrect."],
  }),

  compactHelpArticle({
    id: "task-statuses", category: "tasks-automation", title: "What do task statuses mean?",
    summary: "Queued waits for a worker, Running is active, Paused waits for you, Blocked waits for a dependency, and Failed needs attention.",
    explanation: "Tasks are durable, so their state survives navigation and restart. Succeeded and cancelled tasks remain in history. Partial success means useful work completed but some items need review.",
    steps: ["Use Active for queued and running work.", "Use Needs attention for blocked, failed, or review states.", "Open a task for its dependency and latest detail.", "Use History for completed attempts."],
    path: "Tasks → Active / Needs attention / History",
    plan: ["Persist state and progress.", "Run when dependencies and resources are ready.", "Record a terminal result and diagnostics."],
    related: ["pause-resume-cancel", "blocked-task", "tasks-failures"],
    visual: ["tasks", "Active / Needs attention / History", "The three views separate current work, blockers, and retained history."],
  }),
  compactHelpArticle({
    id: "pause-resume-cancel", category: "tasks-automation", title: "When can I pause, resume, or cancel a task?",
    summary: "Only tasks that declare the operation safe expose it; stopping a task never means deleting already validated output.",
    explanation: "Pause preserves resumable progress. Cancel requests a safe stopping point and records cancellation. Some database, migration, or atomic publishing steps cannot be interrupted without risking consistency.",
    steps: ["Open the task detail.", "Read whether it is cancellable or pausable.", "Use Pause for temporary resource control.", "Use Cancel only when you no longer want the result."],
    path: "Tasks → active task → Pause / Resume / Cancel",
    plan: ["Record the requested control action.", "Stop at a safe checkpoint.", "Keep validated prior output and resumable state."],
    related: ["task-statuses", "closing-vault-background-work", "blocked-task"],
    visual: ["tasks", "Pause", "Unavailable controls mean the current operation cannot stop safely."],
  }),
  compactHelpArticle({
    id: "blocked-task", category: "tasks-automation", title: "Why is a task blocked instead of failed?",
    summary: "Blocked means the work is still valid but cannot start until a named model, dependency, approval, or resource becomes available.",
    explanation: "Unlike failure, blocked work usually does not need a new job. Fix the dependency and Vault can resume it. The task detail identifies setup-required, local-model, dependency, or manual-review blocks.",
    steps: ["Open the blocked task.", "Read the dependency or approval detail.", "Fix that prerequisite in Settings or the referenced feature.", "Return to Tasks and confirm automatic resumption."],
    path: "Tasks → Needs attention → blocked task → dependency",
    plan: ["Retain the queued payload.", "Poll or subscribe to dependency readiness.", "Resume the same task when the block clears."],
    related: ["model-unavailable", "task-statuses", "odin-interpretation"],
    visual: ["tasks", "Blocked", "Resolve the named dependency rather than creating repeated retries."],
  }),
  compactHelpArticle({
    id: "task-time-estimates", category: "tasks-automation", title: "Why does a task have no time estimate or a changing estimate?",
    summary: "Estimates appear only after Vault has enough progress data, and they change when file complexity, model speed, or resource contention changes.",
    explanation: "Document pages, OCR, embeddings, graphs, and model generations have different cost distributions. Counts are usually more reliable than an early time estimate.",
    steps: ["Use completed and total counts first.", "Wait for the task to process a representative sample.", "Check whether another model-heavy task is running.", "Investigate only when progress and status detail stop changing."],
    path: "Tasks → active task → Progress and estimated remaining",
    plan: ["Measure completed work and elapsed time.", "Estimate remaining work from current throughput.", "Revise the estimate as workload characteristics change."],
    related: ["task-statuses", "why-model-slow", "closing-vault-background-work"],
    visual: ["tasks", "Estimated remaining", "Progress counts remain meaningful before a stable time estimate exists."],
  }),

  compactHelpArticle({
    id: "model-roles", category: "models-ocr", title: "Why does Vault need chat, embedding, and OCR models?",
    summary: "They do different work: chat writes answers, embeddings retrieve by meaning, and OCR reads text from pixels.",
    explanation: "One ready model does not make every feature ready. Search and clustering depend on embeddings; conversational synthesis and interpretation depend on chat; scanned documents depend on OCR.",
    steps: ["Open Settings → Models & search.", "Review each runtime separately.", "Set up only the roles your workflows need.", "Use System health to confirm their active state."],
    path: "Settings → Models & search",
    plan: ["Route each job to its required runtime.", "Keep failures isolated by model role.", "Expose feature readiness from the actual dependency."],
    related: ["choose-local-model", "model-unavailable", "scanned-documents-ocr"],
    visual: ["models", "Chat / Embeddings / OCR", "Each readiness row enables a different group of Vault features."],
  }),
  compactHelpArticle({
    id: "choose-local-model", category: "models-ocr", title: "How should I choose a local chat model?",
    summary: "Use Vault's hardware recommendation, then balance answer quality, context size, memory use, and speed for your typical questions.",
    explanation: "The largest model that fits is not always the best daily choice. A model with adequate context and stable speed produces a better experience than one that continually exhausts memory or falls back.",
    steps: ["Open the hardware recommendation.", "Choose the recommended compatible model first.", "Test it with a known cited question.", "Change models only after comparing quality and measured speed."],
    path: "Settings → Models & search → Chat model recommendation",
    plan: ["Inspect CPU, GPU, and available memory.", "Filter compatible model formats and sizes.", "Recommend a stable operating point."],
    related: ["why-model-slow", "model-unavailable", "model-download-import"],
    visual: ["models", "Recommended", "Start with the compatible recommendation before manually tuning model size."],
  }),
  compactHelpArticle({
    id: "model-download-import", category: "models-ocr", title: "What is the difference between downloading and importing a model?",
    summary: "Download obtains a supported model through Vault; Import registers a compatible model file already on this computer.",
    explanation: "Both should use durable progress and verify the final artifact. Imported models still need format, architecture, tokenizer, and runtime compatibility checks before activation.",
    steps: ["Use Download for a recommended model you do not have.", "Use Import local model for an existing compatible file.", "Choose a model storage folder with enough space.", "Wait for verification before activating it."],
    path: "Settings → Models & search → Download or Import local model",
    plan: ["Transfer or inspect the model artifact.", "Validate compatibility and integrity.", "Register metadata.", "Activate only after a runtime probe succeeds."],
    related: ["choose-local-model", "model-storage-location", "model-unavailable"],
    visual: ["models", "Download / Import", "Both paths verify the model before making it available to Chat."],
  }),
  compactHelpArticle({
    id: "why-model-slow", category: "models-ocr", title: "Why is the local model slow?",
    summary: "Speed depends on model size, context length, CPU/GPU support, memory pressure, and other active model jobs.",
    explanation: "The first answer can also include model loading time. Long conversations and broad retrieval increase prompt processing. A smaller compatible model or narrower question often helps more than restarting repeatedly.",
    steps: ["Check System health for the active runtime and acceleration.", "Try a shorter scoped conversation.", "Pause other model-heavy tasks.", "Compare measured speed with the model recommendation."],
    path: "Settings → System health → Local model; Chat → narrow scope",
    plan: ["Load the model into available memory.", "Process retrieved context.", "Generate tokens at hardware-dependent throughput."],
    related: ["choose-local-model", "task-time-estimates", "odin-turbovec"],
    visual: ["models", "Estimated speed", "Model speed should be interpreted together with context size and active workload."],
  }),
  compactHelpArticle({
    id: "model-unavailable", category: "models-ocr", title: "What should I do when Chat says the model is unavailable?",
    summary: "Open model readiness, resolve setup or runtime failure, and retry the interrupted answer after the model reports Ready.",
    explanation: "The conversation and user message remain stored. Unavailable can mean no active model, incompatible hardware, failed loading, missing files, or a managed runtime that is restarting.",
    steps: ["Open Settings from the Chat warning.", "Check the active chat model and runtime detail.", "Activate or repair a compatible model.", "Return to Chat and use Retry."],
    path: "Chat warning → Settings → Models & search → activate or repair",
    plan: ["Preserve the conversation and failed generation state.", "Recover the model runtime.", "Retry from the linked user message without duplicating history."],
    related: ["model-roles", "regenerate-chat-answer", "restart-services"],
    visual: ["models", "Chat model needs setup", "Resolve model readiness before retrying the stored user message."],
  }),
  compactHelpArticle({
    id: "ocr-language-quality", category: "models-ocr", title: "How do language and image quality affect OCR?",
    summary: "OCR is most accurate when the configured language matches clear, upright, high-contrast text.",
    explanation: "Mixed languages, handwriting, tables, faint scans, skew, compression, and unusual layouts reduce accuracy. OCR output should be checked before using exact names, numbers, or quotations.",
    steps: ["Choose the appropriate OCR language support.", "Prefer scans near their original resolution.", "Correct rotation and contrast before reindexing.", "Verify critical text against the image page."],
    path: "Settings → Models & search → OCR; Source → Pages",
    plan: ["Preprocess the page image.", "Recognize text with configured language data.", "Align output to page order and retain the original for verification."],
    related: ["scanned-documents-ocr", "open-citation", "retry-failed-source"],
    visual: ["models", "OCR language", "The original scanned page remains the authority for uncertain OCR text."],
  }),

  compactHelpArticle({
    id: "vault-storage-location", category: "storage-backups", title: "Where does Vault store my library?",
    summary: "The active vault path contains the library database and managed derived data; model storage can use a separate location.",
    explanation: "Settings shows the authoritative path. The hidden .vault directory is managed application data and should not be edited manually while Vault is running.",
    steps: ["Open Settings → Profile or Library & security.", "Read the displayed library path.", "Use Vault's move and backup actions instead of moving internal files manually.", "Review model storage separately under Models & search."],
    path: "Settings → Library & security → Library location",
    plan: ["Resolve one active vault path.", "Keep database and derived files together.", "Validate identity before opening or moving it."],
    related: ["move-vault", "backup-vault", "model-storage-location"],
    visual: ["storage", "Library location", "The path shown in Settings is the active library Vault will open next time."],
  }),
  compactHelpArticle({
    id: "backup-vault", category: "storage-backups", title: "How should I back up a vault?",
    summary: "Use Vault's backup action so the database and required managed files are captured from a consistent state.",
    explanation: "Copying an active database directory manually can capture mismatched files. A backup is especially important before moving, deleting, resetting security, or performing major repairs.",
    steps: ["Open Settings → Library & security.", "Choose Create backup.", "Save it outside the active vault directory.", "Verify the backup completes and record its date before destructive work."],
    path: "Settings → Library & security → Create backup",
    plan: ["Checkpoint active database state.", "Collect required managed files.", "Write and validate the backup artifact without changing the active vault."],
    related: ["restore-backup", "move-vault", "delete-vault"],
    visual: ["storage", "Create backup", "Store backups outside the library they are protecting."],
  }),
  compactHelpArticle({
    id: "restore-backup", category: "storage-backups", title: "How do I recover from a vault backup?",
    summary: "Restore into a safe destination, validate it as a vault, then select it through the setup or recovery flow.",
    explanation: "Do not overwrite a healthy active vault while testing a backup. Recovery may require the original passphrase or vendor recovery material when vault security is enabled.",
    steps: ["Keep the current vault untouched.", "Use the recovery or restore flow to choose the backup.", "Restore into a new folder.", "Unlock and verify source counts, chats, and project readiness before retiring the old vault."],
    path: "Startup recovery → Restore or choose existing library",
    plan: ["Validate backup format and integrity.", "Restore to a non-overlapping path.", "Open only after identity and database checks succeed."],
    related: ["backup-vault", "vault-lock-passphrase", "no-library-selected"],
    visual: ["storage", "Restore library", "Restore beside the existing vault first so recovery remains reversible."],
  }),
  compactHelpArticle({
    id: "move-vault", category: "storage-backups", title: "How do I move my vault to another folder or drive?",
    summary: "Use the Library move action, which copies, verifies, switches the active pointer, and only then retires the old location.",
    explanation: "The destination cannot be a drive root, overlap the source, or contain an incompatible vault. External drives must remain available whenever Vault starts.",
    steps: ["Create a backup.", "Open Settings → Library & security → Move library.", "Choose an empty non-root destination with enough space.", "Wait for copy verification and the active-path switch."],
    path: "Settings → Library & security → Move library",
    plan: ["Validate source and destination paths.", "Copy without changing the active pointer.", "Verify the copied database and files.", "Commit the new pointer only after success."],
    related: ["backup-vault", "vault-storage-location", "low-disk-space"],
    visual: ["storage", "Move library", "Vault verifies the destination before it becomes active."],
  }),
  compactHelpArticle({
    id: "low-disk-space", category: "storage-backups", title: "What happens when disk space is low?",
    summary: "Imports, model downloads, backups, and index publishing may pause or fail safely rather than leave partial active data.",
    explanation: "Original sources, extracted text, embeddings, project snapshots, models, and backups can each be large. Free space on both the vault and model storage locations matters.",
    steps: ["Open System health and Tasks for disk diagnostics.", "Check both library and model storage drives.", "Remove unneeded external backups or unused models through their managed controls.", "Retry the blocked task after space is available."],
    path: "Settings → System health; Settings → Models & search; Tasks",
    plan: ["Estimate required write space.", "Avoid publishing incomplete artifacts.", "Retain prior valid data and expose a retryable diagnostic."],
    related: ["model-storage-location", "task-statuses", "backup-vault"],
    visual: ["storage", "Storage needs attention", "Free space before retrying large imports, models, or project rebuilds."],
  }),
  compactHelpArticle({
    id: "model-storage-location", category: "storage-backups", title: "Can models be stored outside the vault?",
    summary: "Yes. Model storage is separate so large reusable model files do not need to live inside every vault.",
    explanation: "Moving or deleting a vault should not silently delete shared model files. The selected model root must remain readable and have enough space for downloads and temporary verification files.",
    steps: ["Open Settings → Models & search.", "Review or choose the model storage folder.", "Use a stable local drive where possible.", "Re-scan models after moving files through supported controls."],
    path: "Settings → Models & search → Model storage",
    plan: ["Persist the selected model root in desktop setup.", "Scan compatible artifacts.", "Keep model identity separate from vault identity."],
    related: ["model-download-import", "vault-storage-location", "low-disk-space"],
    visual: ["storage", "Model storage", "Models can be shared across vaults while library data stays in its own path."],
  }),

  compactHelpArticle({
    id: "what-is-bridge", category: "connections-sharing", title: "What does Code Connections or Bridge do?",
    summary: "It lets approved external AI tools read selected Vault context and optionally propose or save reviewed outputs.",
    explanation: "Bridge does not automatically expose the whole vault. Connection setup defines allowed vaults, clusters, raw-snippet access, and write capabilities. Review surfaces remain part of the security boundary.",
    steps: ["Open Bridge or Settings → Code connections.", "Choose the minimum required access.", "Connect the external tool.", "Review activity and revoke the connection when it is no longer needed."],
    path: "Bridge; Settings → Code connections",
    plan: ["Authenticate the local or remote client.", "Apply connection scopes to every request.", "Gate review-required writes before committing them."],
    related: ["connection-scopes", "connection-write-approval", "revoke-connection"],
    visual: ["connections", "Connect", "Connection setup starts with scope, not unrestricted access."],
  }),
  compactHelpArticle({
    id: "connection-scopes", category: "connections-sharing", title: "How should I choose connection permissions?",
    summary: "Grant only the vaults, clusters, evidence detail, and write actions required by the external workflow.",
    explanation: "Metadata, profiles, raw snippets, and write-back have different sensitivity. A tool that only needs cluster summaries should not receive raw source passages or global vault access.",
    steps: ["Identify the exact external task.", "Choose the smallest vault or cluster set.", "Leave raw snippets and writes off unless required.", "Review activity after the first use."],
    path: "Settings → Code connections → Connection access",
    plan: ["Store explicit allowed scope IDs.", "Authorize each request against them.", "Reject access outside the connection contract."],
    related: ["what-is-bridge", "connection-write-approval", "privacy-local"],
    visual: ["connections", "Connection access", "Start narrow and expand only when a real workflow requires it."],
  }),
  compactHelpArticle({
    id: "connection-write-approval", category: "connections-sharing", title: "Why does an external write need review?",
    summary: "Review prevents a connected assistant from silently changing source organization or saving untrusted output as vault evidence.",
    explanation: "Some captures can be stored as external artifacts, while trusted reuse or changes to managed data need explicit approval. The review explains what will be created, changed, or kept gated.",
    steps: ["Open the pending review.", "Inspect the proposed content and destination.", "Approve only if the source and scope are correct.", "Reject or keep gated when provenance is unclear."],
    path: "Bridge → Review → pending write",
    plan: ["Capture the proposal without applying it.", "Display provenance, scope, and effect.", "Commit only after an explicit decision."],
    related: ["connection-scopes", "what-is-bridge", "revoke-connection"],
    visual: ["connections", "Review", "Approval is required before review-gated external output changes the vault."],
  }),
  compactHelpArticle({
    id: "odin-pairing", category: "connections-sharing", title: "Why does the Odin command line need pairing?",
    summary: "Pairing gives a specific local CLI client a revocable credential and explicit project scopes without exposing the desktop backend token.",
    explanation: "The request shows the executable identity, computer name, and requested scopes. Approve only a command you just initiated on a computer you recognize.",
    steps: ["Run odin auth pair in the intended terminal.", "Return to Vault and review the pairing request.", "Approve the requested scopes.", "Run odin auth status to confirm the connection."],
    path: "Terminal → odin auth pair; Vault → pairing approval",
    commands: [{ command: "odin auth pair", description: "Request a new local pairing." }, { command: "odin auth status", description: "Verify the active credential." }],
    plan: ["Create a short-lived challenge.", "Require approval in the trusted desktop UI.", "Issue a scoped client credential through secure local storage."],
    related: ["revoke-connection", "connection-scopes", "folder-import-vs-project"],
    visual: ["connections", "Approve", "Approve only the pairing request that matches the terminal you just used."],
  }),
  compactHelpArticle({
    id: "revoke-connection", category: "connections-sharing", title: "How do I disconnect or revoke an external tool?",
    summary: "Revoke its client or connection credential; do not rely only on closing the external application.",
    explanation: "Revocation prevents future authenticated requests. Rotating a credential is useful when the same trusted client should continue with a new secret; deletion is appropriate when access should end.",
    steps: ["Open Settings → Code connections.", "Find the client or connection.", "Choose Revoke or Disconnect.", "Confirm activity stops and pair again only if needed."],
    path: "Settings → Code connections → client → Revoke",
    commands: [{ command: "odin auth logout", description: "Remove this terminal's stored credential." }, { command: "odin auth forget", description: "Forget stale local pairing state." }],
    plan: ["Invalidate the server-side client record.", "Reject future requests using that credential.", "Retain audit history without retaining usable secrets."],
    related: ["what-is-bridge", "odin-pairing", "connection-scopes"],
    visual: ["connections", "Revoke", "Revocation ends future access even if the external process remains open."],
  }),

  compactHelpArticle({
    id: "vault-lock-passphrase", category: "privacy-security", title: "What does locking the vault protect?",
    summary: "Locking prevents Vault from opening protected library material until the correct passphrase or recovery flow succeeds.",
    explanation: "A lock is different from closing a view or signing out of a connection. Forgetting a passphrase can make encrypted data unrecoverable without configured recovery material.",
    steps: ["Set a memorable strong passphrase and store recovery material safely.", "Use Ctrl/Cmd+L or Lock library when leaving the computer.", "Unlock inside the dedicated lock screen.", "Use Reset or recover only after reading its data consequences."],
    path: "Command palette → Lock library; Lock screen → Unlock",
    plan: ["Remove active decryption access from the running app.", "Require local authorization before reopening protected data.", "Keep connection and recovery policies separate."],
    related: ["vault-encryption", "restore-backup", "privacy-local"],
    visual: ["settings", "Lock library", "Lock before leaving a protected vault open on a shared computer."],
  }),
  compactHelpArticle({
    id: "vault-encryption", category: "privacy-security", title: "What does vault encryption cover—and not cover?",
    summary: "Vault encryption protects managed vault material at rest; files outside the vault and anything you explicitly export follow their own storage security.",
    explanation: "Operating-system access, backups, model files, diagnostic exports, clipboard contents, and connected tools have separate boundaries. Encryption does not replace device security or careful sharing.",
    steps: ["Review the active vault path and security status.", "Protect backups and recovery material separately.", "Review exports before sharing.", "Use connection scopes for external tools."],
    path: "Settings → Library & security",
    plan: ["Encrypt protected managed fields and secrets.", "Use operating-system secure storage for credentials.", "Expose separate controls for data that leaves the vault."],
    related: ["vault-lock-passphrase", "diagnostic-privacy", "connection-scopes"],
    visual: ["settings", "Library security", "Encryption is one layer in a wider device, backup, and sharing boundary."],
  }),
  compactHelpArticle({
    id: "diagnostic-privacy", category: "privacy-security", title: "What can a diagnostic bundle contain?",
    summary: "Diagnostics can include versions, health states, bounded logs, job errors, and configuration metadata needed to investigate a problem.",
    explanation: "A well-formed bundle avoids credentials and limits oversized paths or stack details, but filenames, vault identifiers, and error context may still be sensitive. Review it before sharing.",
    steps: ["Create the diagnostic bundle only when needed.", "Open or inspect its contents.", "Remove or withhold anything inappropriate for the recipient.", "Share through a trusted channel."],
    path: "Settings → Advanced → Create diagnostic bundle",
    plan: ["Collect bounded operational evidence.", "Exclude secrets and raw backend tokens.", "Write a user-controlled export for review."],
    related: ["vault-encryption", "find-diagnostics", "privacy-local"],
    visual: ["settings", "Create diagnostic bundle", "Diagnostics should be reviewed like any other exported file."],
  }),

  compactHelpArticle({
    id: "no-library-selected", category: "troubleshooting", title: "Why does Vault say no library is selected?",
    summary: "The desktop setup has no valid active vault pointer, or the saved vault path is missing or unavailable.",
    explanation: "This can happen after moving a folder manually, disconnecting an external drive, clearing setup state, or opening a backup on another computer. Do not create a new empty vault over existing data.",
    steps: ["Confirm the expected drive and folder are available.", "Use Choose existing library or recovery.", "Select the folder that contains the valid .vault database.", "Create a new vault only if no existing library should be recovered."],
    path: "Startup setup or recovery → Choose existing library",
    plan: ["Validate the saved path and database identity.", "Fall back to setup when it is unsafe to open.", "Restore the active pointer only after validation."],
    related: ["restore-backup", "vault-storage-location", "backend-offline"],
    visual: ["storage", "Choose existing library", "Point Vault to the existing library instead of creating another one over it."],
  }),
  compactHelpArticle({
    id: "backend-offline", category: "troubleshooting", title: "What should I do when the Vault service is offline?",
    summary: "Use System health or the startup repair surface; repeated refreshes cannot repair a backend that failed identity or readiness checks.",
    explanation: "The desktop validates that the local service is authenticated, loopback-only, in the correct mode, and opened on the expected vault paths. A different process on the same port is not accepted as Vault.",
    steps: ["Open System health if the application shell is available.", "Use Restart local services once.", "Read the phase-specific startup repair message.", "Create diagnostics if readiness still fails."],
    path: "Settings → System health → Vault service; Startup repair",
    plan: ["Stop owned runtime processes safely.", "Launch the managed backend.", "Verify identity, mode, authentication, and vault paths.", "Reconnect the renderer only after readiness passes."],
    related: ["restart-services", "find-diagnostics", "no-library-selected"],
    visual: ["settings", "Vault service", "Health identifies whether the failure is startup, identity, authentication, or vault selection."],
  }),
  compactHelpArticle({
    id: "find-diagnostics", category: "troubleshooting", title: "Where should I look when something behaves incorrectly?",
    summary: "Start with the affected item's detail, then Tasks, System health, and finally a diagnostic bundle.",
    explanation: "The nearest error is usually the most specific: source inspector for ingestion, project readiness for Odin, answer warnings for Chat, and task detail for background work. System-wide restart should come later.",
    steps: ["Open the affected source, chat, project, map item, or task.", "Read the newest specific error or warning.", "Check the named dependency in System health.", "Create diagnostics only when the cause remains unclear."],
    path: "Affected item → Tasks → System health → Advanced diagnostics",
    plan: ["Preserve local feature diagnostics.", "Link background failures to durable tasks.", "Escalate from narrow evidence to system-wide logs."],
    related: ["task-statuses", "backend-offline", "diagnostic-privacy"],
    visual: ["settings", "Needs attention", "Begin with the closest specific error before restarting or rebuilding broad systems."],
  }),
  compactHelpArticle({
    id: "sync-folder-changes", category: "sources-imports", title: "How do folder imports pick up added, changed, or deleted files?",
    summary: "Folder synchronization compares the registered root with its last known state and applies changes as durable source jobs.",
    explanation: "Adding a file creates a source, changing a file creates a new ingestion generation, and deleting a file can require confirmation depending on sync policy. Automatic, notify, and manual modes determine when changes are applied.",
    steps: ["Open Settings → Code connections or the folder's sync controls.", "Review its sync mode and last scan.", "Scan for changes.", "Approve or apply the reported additions, updates, and removals."],
    path: "Settings → Code connections → Folder sync → Scan or Apply",
    plan: ["Fingerprint supported files under the registered root.", "Compare them with stored source identities.", "Queue minimal additions and updates while handling removals according to policy."],
    related: ["folder-import-vs-files", "batch-upload-progress", "delete-source-effects"],
    visual: ["sources", "Scan for changes", "Review detected removals before a maintained folder changes source membership."],
  }),
  compactHelpArticle({
    id: "chat-history-saving", category: "chat-answers", title: "What happens when I save, rename, or delete a chat?",
    summary: "Saving marks a conversation for easier retrieval, renaming changes its label, and deleting removes that conversation—not its cited sources.",
    explanation: "Chat scope, messages, generations, citations, and feedback belong to the conversation. Deleting it does not delete sources, clusters, projects, or model files. Saved is an organizational flag rather than a separate backup.",
    steps: ["Rename the title at the top of the chat.", "Use Save for conversations you want to find quickly.", "Open chat history to return later.", "Use the confirmed Delete action only when the conversation history is no longer needed."],
    path: "Chat → title / Save / Delete; Chat history → saved conversation",
    plan: ["Persist title, scope, messages, and citations together.", "Update the saved flag without copying the conversation.", "Delete chat-owned records while preserving all source evidence."],
    related: ["choose-chat-scope", "open-citation", "chat-attachments"],
    visual: ["chat", "Save", "Saving helps organize a chat; it does not change its retrieval scope or duplicate it."],
  }),
];

export const helpArticles: HelpArticle[] = [
  {
    id: "first-ten-minutes",
    category: "getting-started",
    title: "What should I do in my first ten minutes?",
    summary: "Add a small set of useful sources, wait for indexing, then ask one focused question.",
    explanation: [
      "Vault works best when you begin with material you already understand. A small first import makes it easy to confirm that extraction, clustering, and chat citations are behaving as expected.",
      "A source marked Ready is searchable and available to chat. Clusters and map connections may appear shortly afterward because they are derived in separate background tasks.",
    ],
    steps: [
      "Open Sources and add three to ten related documents or one folder.",
      "Wait until each source shows Ready.",
      "Open Clusters and review the suggested grouping.",
      "Open Chat, choose the cluster, and ask a question whose answer you know.",
      "Open at least one citation to confirm the answer is grounded in the right source.",
    ],
    path: "Sources → Add files → Clusters → Chat → choose a scope",
    plan: [
      "Vault extracts and indexes each source.",
      "It calculates source similarity and proposes cluster membership.",
      "Chat retrieves evidence only from the scope you select.",
      "Citations preserve the source used for each claim.",
    ],
    related: ["source-statuses", "choose-chat-scope", "how-clustering-works"],
    visual: {
      kind: "sources",
      title: "Start in Sources",
      highlight: "Add files",
      caption: "Add a small, familiar set first so every later result is easy to verify.",
    },
  },
  {
    id: "source-statuses",
    category: "sources-imports",
    title: "What do source statuses mean?",
    summary: "Waiting, Processing, Ready, and Failed describe ingestion—not whether a source is clustered.",
    explanation: [
      "Ingestion and organization are separate. Ready means Vault extracted usable content and indexed it for search and chat. A ready source can still be unclustered while similarity work is queued or while no suitable cluster exists.",
      "Failed means that generation of the source did not finish. Open the source inspector for the recorded error before retrying.",
    ],
    steps: [
      "Open Sources and use the status filter.",
      "Select a source to open its inspector.",
      "Read the ingestion detail and page or chunk counts.",
      "Use Reindex only for a failed or incomplete source.",
    ],
    path: "Sources → select a source → Source details",
    plan: [
      "Waiting: the durable import job has not started this source.",
      "Processing: extraction or indexing is running.",
      "Ready: search and chat can retrieve the source.",
      "Failed: Vault retained the source record and error so you can retry safely.",
    ],
    related: ["ready-not-clustered", "batch-upload-progress", "retry-failed-source"],
    visual: {
      kind: "sources",
      title: "Read the status column",
      highlight: "Ready",
      caption: "Ready confirms indexing. The Cluster column separately shows organization.",
    },
  },
  {
    id: "ready-not-clustered",
    category: "sources-imports",
    title: "Why is a source ready but not clustered?",
    summary: "The source is indexed, but cluster assignment is a separate background step.",
    explanation: [
      "Ready confirms that Vault can search and quote the source. Clustering compares that source with other indexed material and may finish later, especially during a large import.",
      "You do not need to wait for clustering to use the source. Choose Unclustered sources in Chat, or assign the source manually if you already know where it belongs.",
    ],
    steps: [
      "Open Sources and select Unclustered sources.",
      "Select the ready source and inspect its content.",
      "Choose a cluster in the source inspector if the destination is obvious.",
      "Otherwise open Clusters and use Refresh clustering once the import job is idle.",
    ],
    path: "Sources → Unclustered sources → select source → Cluster",
    plan: [
      "Vault keeps the indexed source available immediately.",
      "The clustering job compares its embedding with current cluster profiles.",
      "A confident match assigns the source; an uncertain match remains unclustered for review.",
      "Chat continues to find it when Unclustered sources is the selected scope.",
    ],
    related: ["batch-upload-progress", "ask-unclustered", "how-clustering-works"],
    visual: {
      kind: "sources",
      title: "Ready and Cluster are separate",
      highlight: "Unclustered",
      caption: "Use the cluster selector in the inspector without reimporting the document.",
    },
  },
  {
    id: "batch-upload-progress",
    category: "sources-imports",
    title: "How do I follow a batch upload?",
    summary: "Use the persistent import progress bar and wait for the whole durable job, not only the first file.",
    explanation: [
      "A batch is one durable job with per-file progress. The first document can reach Ready while later documents are still extracting, indexing, or waiting for clustering.",
      "Leaving Sources does not cancel the job. Vault keeps the progress surface visible across routes and reports completed, failed, and remaining counts.",
    ],
    steps: [
      "Add the files or import a folder.",
      "Watch the import progress surface for the total and completed counts.",
      "Do not use Refresh clustering while files are still Processing unless you need an interim grouping.",
      "Review Failed items separately when the job finishes.",
    ],
    path: "Sources → Add files or Import folder → Import progress",
    plan: [
      "Vault queues every supported file before processing begins.",
      "Each file is extracted and indexed independently so one failure does not stop the batch.",
      "Cluster refresh is scheduled after indexed membership changes settle.",
      "The final summary reports anything that still needs attention.",
    ],
    related: ["source-statuses", "ready-not-clustered", "retry-failed-source"],
    visual: {
      kind: "sources",
      title: "Follow the whole import",
      highlight: "7 of 10 ready",
      caption: "The total matters more than the first row that reaches Ready.",
    },
  },
  {
    id: "how-clustering-works",
    category: "clusters",
    title: "How does automatic clustering work?",
    summary: "Vault groups indexed sources by semantic similarity while leaving uncertain material for you to review.",
    explanation: [
      "Cluster membership is derived from source embeddings and the current cluster profile. It is not based only on filenames or folders.",
      "Manual moves remain authoritative. Refresh clustering recalculates suggestions; it should not silently override a deliberate user move without new evidence.",
    ],
    steps: [
      "Open Clusters and compare names, descriptions, and source counts.",
      "Open a cluster to review its Sources tab.",
      "Move an obviously misplaced source using its row action.",
      "Use Refresh clustering after a large import or major source move.",
    ],
    path: "Clusters → open cluster → Sources → Move",
    plan: [
      "Build semantic representations for newly indexed sources.",
      "Compare sources with existing cluster profiles.",
      "Assign high-confidence matches and retain low-confidence sources as unclustered.",
      "Refresh cluster descriptions and connection summaries from current membership.",
    ],
    related: ["ready-not-clustered", "cluster-source-list", "ask-unclustered"],
    visual: {
      kind: "clusters",
      title: "Review before refreshing",
      highlight: "Refresh clustering",
      caption: "Refresh is most useful after the import queue has become idle.",
    },
  },
  {
    id: "cluster-source-list",
    category: "clusters",
    title: "How do I see only the sources in one cluster?",
    summary: "Open the cluster and choose View all sources; Vault carries the cluster filter into Sources.",
    explanation: [
      "The cluster detail page offers a short recent list and a searchable Sources tab. View all sources opens the full Sources workspace while preserving the cluster in the URL.",
      "Selecting a row also preserves that filter, so closing the inspector returns you to the same cluster list.",
    ],
    steps: [
      "Open Clusters and choose the cluster.",
      "Use the Sources tab for a quick search.",
      "Choose View all sources for filters, pagination, and source details.",
    ],
    path: "Clusters → [cluster] → Sources or View all sources",
    plan: [
      "The cluster ID becomes part of the Sources route.",
      "Counts, search, status filters, and pagination use the same cluster ID.",
      "Opening a source retains both the selected source and cluster scope.",
    ],
    related: ["how-clustering-works", "choose-chat-scope", "map-no-connections"],
    visual: {
      kind: "clusters",
      title: "Keep the cluster scope",
      highlight: "View all sources",
      caption: "The breadcrumb and source count confirm that the list is filtered.",
    },
  },
  {
    id: "choose-chat-scope",
    category: "chat-answers",
    title: "How do I control which sources Chat uses?",
    summary: "Use the scope selector above the conversation and verify the scope label below the composer.",
    explanation: [
      "All vault context searches broadly. A cluster, Odin project, or Unclustered sources scope narrows retrieval before the model writes an answer.",
      "The selected scope is stored with the conversation. Existing project chats continue to show the project name so you can tell project retrieval from its underlying source cluster.",
    ],
    steps: [
      "Open Chat and create or open a conversation.",
      "Open the scope selector beside the chat title.",
      "Choose all vault context, unclustered sources, a cluster, or the current Odin project.",
      "Confirm the scope label below the composer before sending.",
    ],
    path: "Chat → scope selector → choose retrieval context",
    plan: [
      "Vault filters candidate evidence by the stored conversation scope.",
      "Retrieval ranks matching chunks within that boundary.",
      "The answer records citations and a coverage ledger for the retrieved evidence.",
    ],
    related: ["ask-unclustered", "open-citation", "odin-interpretation"],
    visual: {
      kind: "chat",
      title: "Check scope before sending",
      highlight: "Browser Start Issues",
      caption: "The selector and composer label should name the same scope.",
    },
  },
  {
    id: "ask-unclustered",
    category: "chat-answers",
    title: "Can Chat answer from unclustered sources?",
    summary: "Yes. Choose Unclustered sources as the conversation scope.",
    explanation: [
      "Unclustered does not mean unavailable. Indexed unclustered sources are searchable and can answer questions without being placed into a semantic cluster first.",
      "This scope is useful after a batch import, when reviewing ambiguous material, or when you want to avoid unrelated established clusters.",
    ],
    steps: [
      "Open Chat.",
      "Choose Unclustered sources in the scope selector.",
      "Ask a focused question and inspect the returned citations.",
      "Move useful sources into clusters later if their destination becomes clear.",
    ],
    path: "Chat → scope selector → Unclustered sources",
    plan: [
      "Vault counts indexed sources whose cluster is empty.",
      "Retrieval searches only those sources.",
      "Citations still open the exact source in the Sources inspector.",
    ],
    related: ["ready-not-clustered", "choose-chat-scope", "open-citation"],
    visual: {
      kind: "chat",
      title: "Select the unclustered scope",
      highlight: "Unclustered sources",
      caption: "The count beside the option shows how many indexed sources are included.",
    },
  },
  {
    id: "open-citation",
    category: "chat-answers",
    title: "How do I verify an answer?",
    summary: "Open a citation and use View source to inspect the exact document behind the claim.",
    explanation: [
      "A useful answer is not enough by itself. Citation popovers show the source title, evidence excerpt, and page or code location when available.",
      "View source opens that specific source—not the global library—so you can compare the answer with the original text.",
    ],
    steps: [
      "Open a citation below the assistant answer.",
      "Read the evidence excerpt and location.",
      "Choose View source.",
      "Compare the source inspector text with the answer before relying on it.",
    ],
    path: "Chat → citation → View source",
    plan: [
      "Each answer stores source IDs with its evidence.",
      "The citation route carries the selected source ID into Sources.",
      "The inspector loads source metadata, pages, and extraction statistics.",
    ],
    related: ["choose-chat-scope", "ask-unclustered", "privacy-local"],
    visual: {
      kind: "chat",
      title: "Follow the evidence",
      highlight: "View source",
      caption: "The source inspector opens directly on the cited document.",
    },
  },
  {
    id: "odin-interpretation",
    category: "odin-projects",
    title: "Why is Odin interpretation unavailable?",
    summary: "Interpretation depends on a current project snapshot, retrieval index, and an available local chat model.",
    explanation: [
      "Structure and retrieval can be Ready while interpretation is still unavailable. Interpretation is a separate derived layer that needs the active snapshot and model runtime to agree on the same project generation.",
      "Use the project status first. Reindex only the missing layer instead of deleting and recreating the project.",
    ],
    steps: [
      "Open the Odin project and read each readiness row.",
      "Open Settings → Models & search and confirm the chat model is Ready.",
      "Run Odin status or doctor for a terminal-side explanation.",
      "Reindex the interpretation layer if structure and retrieval are current.",
    ],
    path: "Projects → [project] → Intelligence readiness",
    commands: [
      { command: "odin doctor", description: "Check pairing, runtimes, and project prerequisites." },
      { command: "odin project status [path]", description: "Show snapshot and derived-layer readiness." },
      { command: "odin project reindex [path] --layer interpretation", description: "Rebuild only interpretation." },
    ],
    plan: [
      "Validate the active project snapshot and manifest.",
      "Confirm structure and retrieval refer to that snapshot.",
      "Run interpretation with the configured local chat model.",
      "Publish the new interpretation only after validation succeeds.",
    ],
    related: ["odin-turbovec", "odin-graph-metrics", "restart-services"],
    visual: {
      kind: "project",
      title: "Read each project layer",
      highlight: "Interpretation unavailable",
      caption: "The readiness rows identify the missing layer without discarding healthy work.",
    },
  },
  {
    id: "odin-turbovec",
    category: "odin-projects",
    title: "When should TurboVec activate?",
    summary: "TurboVec activates only after its benchmark shows a reliable benefit for the active vault and hardware.",
    explanation: [
      "Source count alone does not force activation. Vault considers corpus size, benchmark results, hardware compatibility, index freshness, and the runtime safety gate.",
      "If the vault qualifies but activation is absent, System health and the benchmark record should explain which gate is still pending or failed.",
    ],
    steps: [
      "Open Settings → System health.",
      "Find embedding and TurboVec readiness.",
      "Confirm no benchmark or model-runtime task is failed in Tasks.",
      "Run doctor before forcing a rebuild.",
    ],
    path: "Settings → System health → Vector search",
    commands: [
      { command: "odin doctor", description: "Report runtime and acceleration blockers." },
      { command: "odin project status [path]", description: "Confirm the project retrieval snapshot is current." },
    ],
    plan: [
      "Measure the active corpus and current retrieval latency.",
      "Benchmark the compatible accelerated path.",
      "Activate only when correctness passes and the benefit clears the safety threshold.",
      "Keep the current index available if activation or rollback validation fails.",
    ],
    related: ["odin-interpretation", "odin-graph-metrics", "tasks-failures"],
    visual: {
      kind: "settings",
      title: "Check the activation gates",
      highlight: "Vector search",
      caption: "Health details should name the current runtime and any pending benchmark.",
    },
  },
  {
    id: "odin-graph-metrics",
    category: "odin-projects",
    title: "Why do project graph metrics fail?",
    summary: "Metrics require a valid current graph snapshot; repeated failure usually points to stale graph data or a blocked model task.",
    explanation: [
      "Graph construction and metric generation are separate tasks. A project can open while its newest metric run has failed, because Vault keeps the last validated snapshot available.",
      "Check the newest task, not the historical failure count. A later successful run supersedes earlier failures without deleting their diagnostic history.",
    ],
    steps: [
      "Open Tasks and filter to Needs attention.",
      "Open the newest project graph metrics task.",
      "Confirm the project graph snapshot is current.",
      "Retry once after resolving the named dependency; avoid repeated blind retries.",
    ],
    path: "Tasks → Needs attention → newest Project graph metrics task",
    commands: [
      { command: "odin project status [path]", description: "Check graph and snapshot freshness." },
      { command: "odin project reindex [path] --layer structure", description: "Rebuild structure when the graph is stale." },
    ],
    plan: [
      "Load the current validated project graph.",
      "Compute graph-wide metrics outside the request timeout.",
      "Validate counts and references against the same snapshot.",
      "Publish atomically and retain the prior good metrics on failure.",
    ],
    related: ["odin-interpretation", "tasks-failures", "restart-services"],
    visual: {
      kind: "project",
      title: "Use the newest task",
      highlight: "Graph metrics",
      caption: "Historical failures remain visible, but the newest run determines current readiness.",
    },
  },
  {
    id: "map-no-connections",
    category: "map-connections",
    title: "Why does the map show no connections?",
    summary: "Connections appear only after the selected mode has valid edges for the visible sources.",
    explanation: [
      "Current connections come from stored relationships. Semantic connections are calculated from source similarity and may use a minimum score. A map can contain nodes but no visible edges when the wrong mode, a narrow filter, or an unfinished relationship job removes every edge.",
      "Use the legend and selected mode before assuming data is missing. Expanding the view should request more relevant items and their edges together.",
    ],
    steps: [
      "Open Map and clear search or cluster filters.",
      "Switch between Current and Semantic connections.",
      "Select a source and inspect its connection count.",
      "Use Show more to expand the relevant neighborhood.",
      "Check Tasks if both modes remain empty for known-related sources.",
    ],
    path: "Map → connection mode → select source → Show more",
    plan: [
      "Load the question-relevant source set.",
      "Fetch edges whose endpoints are both present in that set.",
      "Apply the chosen current or semantic threshold.",
      "Render edges and expose their evidence in the selected-source details.",
    ],
    related: ["map-show-more", "how-clustering-works", "tasks-failures"],
    visual: {
      kind: "map",
      title: "Check the connection mode",
      highlight: "Semantic connections",
      caption: "The legend distinguishes stored links from similarity-based links.",
    },
  },
  {
    id: "map-show-more",
    category: "map-connections",
    title: "What does Show more add to the map?",
    summary: "It expands the result set with the next sources relevant to the current question or selection.",
    explanation: [
      "The first map view is bounded so it remains readable and responsive. Show more continues the same ranked query; it should not restart with unrelated global sources.",
      "The final expansion can include every source that clears the relevance rule, while the viewport may still simplify labels or hide details until selection.",
    ],
    steps: [
      "Ask the project map a specific question or select a source.",
      "Inspect the first result set and its connection mode.",
      "Choose Show more and confirm the existing nodes remain.",
      "Continue until the control reports that all relevant sources are shown.",
    ],
    path: "Project map → ask a question → Show more",
    plan: [
      "Rank sources against the active map question.",
      "Return a bounded first page for legibility.",
      "Append later pages without changing the query or dropping prior nodes.",
      "Stop when no relevant ranked sources remain.",
    ],
    related: ["map-no-connections", "odin-graph-metrics", "choose-chat-scope"],
    visual: {
      kind: "map",
      title: "Expand the same answer",
      highlight: "Show more",
      caption: "Existing relevant nodes remain while the next ranked page is added.",
    },
  },
  {
    id: "privacy-local",
    category: "privacy-security",
    title: "What stays local, and what can leave Vault?",
    summary: "Your vault, indexes, and local-model conversations stay on this computer unless you explicitly connect or export them.",
    explanation: [
      "Vault stores the library under its selected vault path and uses local model runtimes by default. Bridge and connected tools have explicit scopes and review surfaces.",
      "Treat exported diagnostics and manually shared snippets as separate artifacts. Review their contents before sending them elsewhere.",
    ],
    steps: [
      "Open Settings → Library & security to review the vault path and lock state.",
      "Open Code connections to review allowed vaults, clusters, and raw-snippet access.",
      "Keep raw snippets disabled unless a workflow requires them.",
      "Review diagnostic bundles before sharing.",
    ],
    path: "Settings → Library & security; Settings → Code connections",
    plan: [
      "Encrypt protected vault material and credentials at rest.",
      "Bind local services to authenticated loopback endpoints.",
      "Require explicit scopes for connected tools.",
      "Keep review-required write-backs gated until you approve them.",
    ],
    related: ["open-citation", "delete-vault", "restart-services"],
    visual: {
      kind: "settings",
      title: "Review connection access",
      highlight: "Connection access",
      caption: "Vault and cluster scopes should match the minimum access the tool needs.",
    },
  },
  {
    id: "retry-failed-source",
    category: "troubleshooting",
    title: "How should I retry a failed source?",
    summary: "Inspect the recorded failure first, then retry that source without reuploading the whole batch.",
    explanation: [
      "Vault retains failed source records so the original path, stage, and diagnostic detail remain available. Reimporting everything can create duplicates and hides whether the original failure was actually resolved.",
      "Password-protected, unreadable, unsupported, or missing files need different fixes. The source inspector identifies the stage that failed.",
    ],
    steps: [
      "Open Sources and filter to Failed.",
      "Select the source and read its failure detail.",
      "Resolve the named file, OCR, model, or storage issue.",
      "Choose Reindex and watch the durable task in Tasks.",
    ],
    path: "Sources → Status: Failed → select source → Reindex",
    plan: [
      "Create a new ingestion generation for the same source.",
      "Preserve the prior failure detail until the new generation succeeds.",
      "Replace derived chunks and embeddings atomically.",
      "Schedule clustering when the source returns to Ready.",
    ],
    related: ["source-statuses", "batch-upload-progress", "tasks-failures"],
    visual: {
      kind: "sources",
      title: "Retry one source",
      highlight: "Reindex",
      caption: "Keep the source record and its diagnostic history instead of uploading a duplicate.",
    },
  },
  {
    id: "tasks-failures",
    category: "troubleshooting",
    title: "Why do old failed tasks still appear?",
    summary: "Tasks keeps diagnostic history; current readiness is determined by the newest run for that work.",
    explanation: [
      "A successful retry does not erase earlier failures. This makes recurring issues diagnosable and prevents a later success from hiding how often a task needed intervention.",
      "Use the status views and timestamps to distinguish a current blocker from historical evidence.",
    ],
    steps: [
      "Open Tasks and choose Needs attention.",
      "Sort mentally by the newest timestamp for the affected feature.",
      "If a newer run succeeded, treat the older failure as history.",
      "If the newest run failed, open it and act on the first specific dependency error.",
    ],
    path: "Tasks → Needs attention → newest matching task",
    plan: [
      "Durable jobs retain attempts and terminal states.",
      "A retry creates a new run with its own timestamps and diagnostics.",
      "Feature readiness reads the newest validated output, not the total failure count.",
    ],
    related: ["odin-graph-metrics", "retry-failed-source", "restart-services"],
    visual: {
      kind: "settings",
      title: "Read the newest attempt",
      highlight: "Needs attention",
      caption: "Timestamps separate current failures from retained history.",
    },
  },
  {
    id: "restart-services",
    category: "troubleshooting",
    title: "What should I do when restart takes longer than expected?",
    summary: "Use the Settings restart action and let the desktop process supervise shutdown and recovery outside normal API timeouts.",
    explanation: [
      "Stopping local models and database work can legitimately take longer than a normal request. Restart and vault deletion therefore use desktop-supervised operations instead of the generic short request timeout.",
      "Avoid force-closing Vault while a deletion confirmation is in progress. A failed pre-vault restart should restore the previous pointer and data rather than leave a half-deleted library.",
    ],
    steps: [
      "Open Settings → Advanced.",
      "Choose Restart local services once.",
      "Watch the persistent progress or recovery surface.",
      "If startup fails, use the displayed repair action or create a diagnostic bundle.",
    ],
    path: "Settings → Advanced → Restart local services",
    plan: [
      "Stop the managed model without applying the generic request timeout.",
      "Stop and relaunch the authenticated local backend.",
      "Verify backend identity and vault paths before reconnecting the UI.",
      "Show a repair surface if readiness cannot be restored.",
    ],
    related: ["tasks-failures", "delete-vault", "odin-interpretation"],
    visual: {
      kind: "settings",
      title: "Let the desktop supervise restart",
      highlight: "Restart local services",
      caption: "The progress surface remains authoritative even when startup takes more than twelve seconds.",
    },
  },
  {
    id: "delete-vault",
    category: "troubleshooting",
    title: "What happens when I delete a vault?",
    summary: "Vault confirms the exact library, stops managed services, tombstones the data, and returns to setup.",
    explanation: [
      "Deleting a vault is intentionally different from deleting a source or cluster. It affects the active library directory and desktop setup state, so Vault requires a dedicated authorization step.",
      "If the restart handoff fails before deletion is committed, Vault restores the prior data and active pointer. Once deletion succeeds, recovery depends on your external backups.",
    ],
    steps: [
      "Create and verify a backup first.",
      "Open Settings → Library & security.",
      "Choose Delete library and read the exact path.",
      "Complete the dedicated confirmation and wait for setup to reopen.",
    ],
    path: "Settings → Library & security → Delete library",
    plan: [
      "Authorize deletion against the active vault identity.",
      "Stop managed model and backend processes.",
      "Move or tombstone vault data before clearing setup state.",
      "Roll back the pointer and data if the pre-deletion handoff fails.",
    ],
    related: ["privacy-local", "restart-services", "tasks-failures"],
    visual: {
      kind: "settings",
      title: "Verify the exact library path",
      highlight: "Delete library",
      caption: "Back up first; the confirmation identifies the active vault rather than using a generic timeout.",
    },
  },
  ...additionalHelpArticles,
];

export function helpArticleById(id?: string) {
  return helpArticles.find((article) => article.id === id) ?? helpArticles[0];
}
