/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTimelineRouteImport } from './routes/_app.timeline'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSourcesRouteImport } from './routes/_app.sources'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppMapRouteImport } from './routes/_app.map'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppClustersRouteImport } from './routes/_app.clusters'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppBridgeRouteImport } from './routes/_app.bridge'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppClustersClusterIdRouteImport } from './routes/_app.clusters.$clusterId'
import { Route as AppChatChatIdRouteImport } from './routes/_app.chat.$chatId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppClustersRoute = AppClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBridgeRoute = AppBridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppClustersClusterIdRoute = AppClustersClusterIdRouteImport.update({
  id: '/$clusterId',
  path: '/$clusterId',
  getParentRoute: () => AppClustersRoute,
} as any)
const AppChatChatIdRoute = AppChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AppChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/activity': typeof AppActivityRoute
  '/bridge': typeof AppBridgeRoute
  '/chat': typeof AppChatRouteWithChildren
  '/clusters': typeof AppClustersRouteWithChildren
  '/home': typeof AppHomeRoute
  '/map': typeof AppMapRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/tasks': typeof AppTasksRoute
  '/timeline': typeof AppTimelineRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/clusters/$clusterId': typeof AppClustersClusterIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/activity': typeof AppActivityRoute
  '/bridge': typeof AppBridgeRoute
  '/chat': typeof AppChatRouteWithChildren
  '/clusters': typeof AppClustersRouteWithChildren
  '/home': typeof AppHomeRoute
  '/map': typeof AppMapRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/tasks': typeof AppTasksRoute
  '/timeline': typeof AppTimelineRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/clusters/$clusterId': typeof AppClustersClusterIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/bridge': typeof AppBridgeRoute
  '/_app/chat': typeof AppChatRouteWithChildren
  '/_app/clusters': typeof AppClustersRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/map': typeof AppMapRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sources': typeof AppSourcesRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/timeline': typeof AppTimelineRoute
  '/_app/chat/$chatId': typeof AppChatChatIdRoute
  '/_app/clusters/$clusterId': typeof AppClustersClusterIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/activity'
    | '/bridge'
    | '/chat'
    | '/clusters'
    | '/home'
    | '/map'
    | '/projects'
    | '/search'
    | '/settings'
    | '/sources'
    | '/tasks'
    | '/timeline'
    | '/chat/$chatId'
    | '/clusters/$clusterId'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/activity'
    | '/bridge'
    | '/chat'
    | '/clusters'
    | '/home'
    | '/map'
    | '/projects'
    | '/search'
    | '/settings'
    | '/sources'
    | '/tasks'
    | '/timeline'
    | '/chat/$chatId'
    | '/clusters/$clusterId'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/activity'
    | '/_app/bridge'
    | '/_app/chat'
    | '/_app/clusters'
    | '/_app/home'
    | '/_app/map'
    | '/_app/projects'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/sources'
    | '/_app/tasks'
    | '/_app/timeline'
    | '/_app/chat/$chatId'
    | '/_app/clusters/$clusterId'
    | '/_app/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clusters': {
      id: '/_app/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof AppClustersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bridge': {
      id: '/_app/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof AppBridgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/clusters/$clusterId': {
      id: '/_app/clusters/$clusterId'
      path: '/$clusterId'
      fullPath: '/clusters/$clusterId'
      preLoaderRoute: typeof AppClustersClusterIdRouteImport
      parentRoute: typeof AppClustersRoute
    }
    '/_app/chat/$chatId': {
      id: '/_app/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AppChatChatIdRouteImport
      parentRoute: typeof AppChatRoute
    }
  }
}

interface AppChatRouteChildren {
  AppChatChatIdRoute: typeof AppChatChatIdRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatChatIdRoute: AppChatChatIdRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppClustersRouteChildren {
  AppClustersClusterIdRoute: typeof AppClustersClusterIdRoute
}

const AppClustersRouteChildren: AppClustersRouteChildren = {
  AppClustersClusterIdRoute: AppClustersClusterIdRoute,
}

const AppClustersRouteWithChildren = AppClustersRoute._addFileChildren(
  AppClustersRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppBridgeRoute: typeof AppBridgeRoute
  AppChatRoute: typeof AppChatRouteWithChildren
  AppClustersRoute: typeof AppClustersRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppMapRoute: typeof AppMapRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSourcesRoute: typeof AppSourcesRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTimelineRoute: typeof AppTimelineRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppBridgeRoute: AppBridgeRoute,
  AppChatRoute: AppChatRouteWithChildren,
  AppClustersRoute: AppClustersRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppMapRoute: AppMapRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSourcesRoute: AppSourcesRoute,
  AppTasksRoute: AppTasksRoute,
  AppTimelineRoute: AppTimelineRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
